### ISSUE TITLE
[Bug] 레포를 Fork한 경우 점수가 엄청나게 올라갑니다

### ISSUE THREAD

**Issue by kdy1** [boostcampwm-2022/web21-devrank#323]
# 📘 설명

순위표 보니까 linux 레포를 포크한 사람들의 점수가 비정상적으로 높았습니다.
아마 포크를 뜬 경우에도 개인 커밋 이력으로 계산되는 것 같아오

# 📗 세부사항

**Comment by Yaminyam** [comment]
linux 레포를 포크하고있는 유저인 skeggsb님을 기준으로 history를 확인해본 결과 "현재기준"으로 정상적으로 산정되고있는 것으로 확인되었습니다
https://docs.github.com/en/graphql/overview/explorer
<img width="665" alt="image" src="https://user-images.githubusercontent.com/31057849/207671714-b50aeb08-c5bf-4298-828b-9087a7a96303.png">

그런데 score History에 남은 14일 기준 6만점대가 어떻게 산정되었던것인지는 다시 알아보고 comment 남기도록 하겠습니다

+ 혹시 문제를 발견하셨던 특정 유저가 있다면 알려주시면 해당 유저기준으로 데이터 확인해보도록 하겠습니다!

**Comment by kdy1** [comment]
레포별로 커밋에 따른 점수가 다른 거였군요
죄송합니다 버그인 줄 알았네요

**Comment by Yaminyam** [comment]
<img width="971" alt="image" src="https://user-images.githubusercontent.com/31057849/207753374-4a76ac2b-38a7-4469-8f16-420f2274dee6.png">

저희 서비스의 가장 큰 특징이라고 생각합니다 ㅎㅎ
star 수가 절대적인 수치는 아니지만 star가 많을수록 많은 사람들에게 이용되고 도움이 될 수 있는 프로젝트에 관한 기여라고 생각했습니다
하지만 star 수가 너무많은 레포에 의한 엄청난 점수 증가를 방지하기 위해 * 0.01 의 가중치를 기여점수에 사용하고 있는데 그럴 경우 star 가 적은 레포가 거의 점수가 없는 문제가 있습니다
그래서 그런 편차를 해결하기 위해 활동점수라는 값을 도입했습니다!

제보해주셔서 감사하고 점수 산정로직에 의견 있으시다면 언제든 환영합니다!
