### ISSUE TITLE
[Bug] CORS 오류 해결

### ISSUE THREAD

**Issue by asdf99245** [boostcampwm-2022/web21-devrank#43]
# 📘 설명

![image](https://user-images.githubusercontent.com/39851220/202341937-143d537e-28b6-412c-9ed7-5d1d5b4901cc.png)
- client에서 server로 요청 시 CORS 오류 발생

# 📗 세부사항

- Client 포트: 8080

**Comment by Yaminyam** [comment]
https://github.com/boostcampwm-2022/web21-devrank/blob/0f157b1ceb833b41cec9a69cf4f16901db9241f8/backend/src/main.ts#L29
cors 설정 되어있습니다
